apiVersion: v1
kind: Service
metadata:
  name: smart-apartment-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: smart-apartment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
